services:
  mysql-db:
    image: mysql:8.0.39
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: cadastro
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-senha_padrao_local} 
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - sistema-network

  api-service:
    build: ./demonstrativo  # <-- Ajustado para o nome da sua pasta
    container_name: api-service
    restart: on-failure
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-senha_padrao_local}
    networks:
      - sistema-network

  front-service:
    build: ./frontend
    container_name: front-service
    restart: always
    ports:
      - "3000:80"
    networks:
      - sistema-network

networks:
  sistema-network:
    driver: bridge
